# Generated by Django 3.2.5 on 2021-09-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdatamodel',
            old_name='username',
            new_name='name',
        ),
    ]
