# Generated by Django 3.2.5 on 2021-09-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0002_rename_username_postdatamodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdatamodel',
            name='number',
        ),
    ]
