# Generated by Django 3.2.5 on 2021-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0007_threadmodel_next_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdatamodel',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
