# Generated by Django 3.2.5 on 2021-09-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0010_alter_postdatamodel_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdatamodel',
            name='response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projectpost.postdatamodel'),
        ),
        migrations.AlterField(
            model_name='postdatamodel',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpost.threadmodel'),
        ),
    ]
