# Generated by Django 3.2.5 on 2021-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0016_alter_postdatamodel_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdatamodel',
            name='response_post_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
